### ISSUE TITLE
Game no longer plays

### ISSUE THREAD

**Issue by kf4x** [castellanos70/StarvationEvasion#23]
I tried testing the server and running a game.

The game no longer advances.

**Comment by max-sanchez** [comment]
Sorry, not sure how that didn't come up during testing. It resulted from an incomplete switch statement in starvationevasion.common.gamecards.GameCard.create(EnumRegion owner, EnumPolicy type). 

I fixed the bug and the game now advances normally with two AIs running, as before. Fix included in commit 83120b886c5362a04619c2cef70af712d9bc8c0a.

**Comment by kf4x** [comment]
Perfect thanks.
